import { Roboto } from "next/font/google";
import "./globals.css";
import Header from "./components/layout/Header";
import { getServerSession } from "next-auth";
import { authOptions } from "./api/auth/[...nextauth]/route";
import SessionProvider from "./components/SessionProvider";

const roboto = Roboto({ 
  weight: ['400', '500', '700'],
  subsets: ["latin"], 
  variable: "--font-roboto" 
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const session = await getServerSession(authOptions);

  return (
    <html lang="en">
      <body className={`${roboto.variable}`}>
        <SessionProvider session={session}>
          <main className="max-w-4xl mx-auto p-4">
            <Header />
            {children}
            <footer className="border-t p-8 text-center text-gray-500 mt-8">
              &copy; 2024 All rights reserved
            </footer>
          </main>
        </SessionProvider>
      </body>
    </html>
  );
}
 