import { Roboto } from "next/font/google";
import "./globals.css";
import Header from "./components/layout/Header";
import AuthProvider from "./components/layout/SessionProvider";

const roboto = Roboto({ subsets: ["latin"], variable: "--font-roboto" });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${roboto.variable}`}>
        <AuthProvider>
          <main className="max-w-4xl mx-auto  p-4">
            <Header />
            {children}
            <footer className="border-t P-8 text-center text-gray-500 mt-8">
              &copy; 2023 All rights reserved
            </footer>
          </main>
        </AuthProvider>
      </body>
    </html>
  );
}
 